name: Testing Secret Variables

on: workflow_dispatch

env:
  ACTION_STEPS_DEBUG: true

jobs:
  test_context_variables:
    runs-on: ubuntu-slim
    steps:
      - name: "Checking Secret Variable"
        run: |
          echo "Secret Value : ${{ secrets.MY_TOP_SEC }}"
          ${{ secrets.MY_TOP_SEC }}
